#################
## Eye Candies ##
#################

## OLED Screen ##
CONFIG_ZMK_DISPLAY=y
# Binary size reduction (compressing images)
CONFIG_LV_USE_RLE=y
# Display sizes
CONFIG_LV_FONT_DEFAULT_MONTSERRAT_20=y
CONFIG_ZMK_LV_FONT_DEFAULT_SMALL_MONTSERRAT_16=y
CONFIG_LV_DPI_DEF=291
# The default ZMK_DISPLAY_DEDICATED_THREAD_STACK_SIZE (3072) is too small for a
# 126x294 RGB888 screen; it silently overflows and freezes.
CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_STACK_SIZE=8192
# ZMK's default UI thread priority is 5, the same as
# ZMK_SPLIT_BLE_PERIPHERAL_PRIORITY and ZMK_BLE_THREAD_PRIORITY. HiDPI RGB
# displays are not particularly fast to render, and with the default priority,
# it can sometimes cause delays in round trips or RGB LED matrix overlays.
CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_PRIORITY=11

############
## Inputs ##
############

CONFIG_INPUT=y
CONFIG_SPI=y

## Trackball ##
CONFIG_ZMK_POINTING=y
CONFIG_PAW3395=y
CONFIG_PAW3395_REPORT_INTERVAL_MIN=1

## Touchpad ##
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y

######################
## Power Management ##
######################

# See "Deep Sleep": https://zmk.dev/docs/features/low-power-states#deep-sleep

CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_TIMEOUT=30000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=600000

#################
## Development ##
#################

CONFIG_INPUT_LOG_LEVEL_INF=y
CONFIG_ZMK_LOG_LEVEL_INF=y
